export const createMapSlice = (set, get) => ({
  currentPosition: { id: "0-0" },
  map: [],
  setPosition: (id) => set(() => ({ currentPosition: { id } })),
  resetPosition: () => set(() => ({ currentPosition: { id: "0-0" } })),
  initializeMap: () =>
      set(() => ({
          map: [
              [
                  { id: "0-0", type: "START", next: ["0-1", "1-0"] },
                  { id: "0-1", type: "BATTLE", next: ["0-2"] },
                  { id: "0-2", type: "BATTLE", next: ["0-3"] },
                  { id: "0-3", type: "BATTLE", next: ["1-3"] },
                  { id: "0-4", type: 0, next: [] },
                  { id: "0-5", type: 0, next: [] },
                  { id: "0-6", type: 0, next: [] },
                  { id: "0-7", type: 0, next: [] },
                  { id: "0-8", type: 0, next: [] },
                  { id: "0-9", type: 0, next: [] },
                  { id: "0-10", type: 0, next: [] },
                  { id: "0-11", type: 0, next: [] },
              ],
              [
                  { id: "1-0", type: "BATTLE", next: ["2-0"] },
                  { id: "1-1", type: 0, next: [] },
                  { id: "1-2", type: 0, next: [] },
                  { id: "1-3", type: "BATTLE", next: ["1-4", "2-3"] },
                  { id: "1-4", type: "BATTLE", next: ["1-5"] },
                  { id: "1-5", type: "BATTLE", next: ["1-6"] },
                  { id: "1-6", type: "BATTLE", next: ["2-6"] },
                  { id: "1-7", type: 0, next: [] },
                  { id: "1-8", type: 0, next: [] },
                  { id: "1-9", type: 0, next: [] },
                  { id: "1-10", type: 0, next: [] },
                  { id: "1-11", type: 0, next: [] },
              ],
              [
                  { id: "2-0", type: "BATTLE", next: ["2-1"] },
                  { id: "2-1", type: "BATTLE", next: ["2-2"] },
                  { id: "2-2", type: "BATTLE", next: ["2-3"] },
                  { id: "2-3", type: "BATTLE", next: ["3-3"] },
                  { id: "2-4", type: 0, next: [] },
                  { id: "2-5", type: 0, next: [] },
                  { id: "2-6", type: "BATTLE", next: ["3-6"] },
                  { id: "2-7", type: 0, next: [] },
                  { id: "2-8", type: 0, next: [] },
                  { id: "2-9", type: 0, next: [] },
                  { id: "2-10", type: 0, next: [] },
                  { id: "2-11", type: 0, next: [] },
              ],
              [
                  { id: "3-0", type: 0, next: [] },
                  { id: "3-1", type: 0, next: [] },
                  { id: "3-2", type: 0, next: [] },
                  { id: "3-3", type: "BATTLE", next: ["4-3"] },
                  { id: "3-4", type: 0, next: [] },
                  { id: "3-5", type: 0, next: [] },
                  { id: "3-6", type: "BATTLE", next: ["4-6"] },
                  { id: "3-7", type: 0, next: [] },
                  { id: "3-8", type: 0, next: [] },
                  { id: "3-9", type: 0, next: [] },
                  { id: "3-10", type: 0, next: [] },
                  { id: "3-11", type: 0, next: [] },
              ],
              [
                  { id: "4-0", type: 0, next: [] },
                  { id: "4-1", type: 0, next: [] },
                  { id: "4-2", type: 0, next: [] },
                  { id: "4-3", type: "BATTLE", next: ["5-3"] },
                  { id: "4-4", type: 0, next: [] },
                  { id: "4-5", type: "BATTLE", next: ["5-5"] },
                  { id: "4-6", type: "BATTLE", next: ["4-5"] },
                  { id: "4-7", type: 0, next: [] },
                  { id: "4-8", type: 0, next: [] },
                  { id: "4-9", type: 0, next: [] },
                  { id: "4-10", type: 0, next: [] },
                  { id: "4-11", type: 0, next: [] },
              ],
              [
                  { id: "5-0", type: 0, next: [] },
                  { id: "5-1", type: 0, next: [] },
                  { id: "5-2", type: 0, next: [] },
                  { id: "5-3", type: "BATTLE", next: ["5-4", "6-3"] },
                  { id: "5-4", type: "SHOP", next: ["5-5"] },
                  { id: "5-5", type: "BATTLE", next: ["6-5"] },
                  { id: "5-6", type: 0, next: [] },
                  { id: "5-7", type: 0, next: [] },
                  { id: "5-8", type: 0, next: [] },
                  { id: "5-9", type: 0, next: [] },
                  { id: "5-10", type: 0, next: [] },
                  { id: "5-11", type: 0, next: [] },
              ],
              [
                  { id: "6-0", type: 0, next: [] },
                  { id: "6-1", type: 0, next: [] },
                  { id: "6-2", type: 0, next: [] },
                  { id: "6-3", type: "BATTLE", next: ["7-3"] },
                  { id: "6-4", type: 0, next: [] },
                  { id: "6-5", type: "BATTLE", next: ["6-6"] },
                  { id: "6-6", type: "BATTLE", next: ["6-7"] },
                  { id: "6-7", type: "EVENT", next: ["6-8"] },
                  { id: "6-8", type: "BATTLE", next: ["7-8"] },
                  { id: "6-9", type: 0, next: [] },
                  { id: "6-10", type: 0, next: [] },
                  { id: "6-11", type: 0, next: [] },
              ],
              [
                  { id: "7-0", type: 0, next: [] },
                  { id: "7-1", type: 0, next: [] },
                  { id: "7-2", type: 0, next: [] },
                  { id: "7-3", type: "BATTLE", next: ["8-3"] },
                  { id: "7-4", type: 0, next: [] },
                  { id: "7-5", type: 0, next: [] },
                  { id: "7-6", type: 0, next: [] },
                  { id: "7-7", type: 0, next: [] },
                  { id: "7-8", type: "BATTLE", next: ["8-8"] },
                  { id: "7-9", type: 0, next: [] },
                  { id: "7-10", type: 0, next: [] },
                  { id: "7-11", type: 0, next: [] },
              ],
              [
                  { id: "8-0", type: 0, next: [] },
                  { id: "8-1", type: 0, next: [] },
                  { id: "8-2", type: 0, next: [] },
                  { id: "8-3", type: "BATTLE", next: ["9-3"] },
                  { id: "8-4", type: 0, next: [] },
                  { id: "8-5", type: 0, next: [] },
                  { id: "8-6", type: 0, next: [] },
                  { id: "8-7", type: 0, next: [] },
                  { id: "8-8", type: "BATTLE", next: ["8-9"] },
                  { id: "8-9", type: "BATTLE", next: ["8-10"] },
                  { id: "8-10", type: "BATTLE", next: ["9-10"] },
                  { id: "8-11", type: 0, next: [] },
              ],
              [
                  { id: "9-0", type: 0, next: [] },
                  { id: "9-1", type: 0, next: [] },
                  { id: "9-2", type: 0, next: [] },
                  { id: "9-3", type: "BATTLE", next: ["10-3"] },
                  { id: "9-4", type: 0, next: [] },
                  { id: "9-5", type: 0, next: [] },
                  { id: "9-6", type: 0, next: [] },
                  { id: "9-7", type: 0, next: [] },
                  { id: "9-8", type: 0, next: [] },
                  { id: "9-9", type: 0, next: [] },
                  { id: "9-10", type: "BATTLE", next: ["10-10"] },
                  { id: "9-11", type: 0, next: [] },
              ],
              [
                  { id: "10-0", type: 0, next: [] },
                  { id: "10-1", type: 0, next: [] },
                  { id: "10-2", type: 0, next: [] },
                  { id: "10-3", type: "BATTLE", next: ["10-4"] },
                  { id: "10-4", type: "BATTLE", next: ["10-5"] },
                  { id: "10-5", type: "BATTLE", next: ["10-6"] },
                  { id: "10-6", type: "BATTLE", next: ["10-7"] },
                  { id: "10-7", type: "BATTLE", next: ["10-8"] },
                  { id: "10-8", type: "BATTLE", next: ["10-9"] },
                  { id: "10-9", type: "BATTLE", next: ["10-10"] },
                  { id: "10-10", type: "BATTLE", next: ["11-10"] },
                  { id: "10-11", type: 0, next: [] },
              ],
              [
                  { id: "11-0", type: 0, next: [] },
                  { id: "11-1", type: 0, next: [] },
                  { id: "11-2", type: 0, next: [] },
                  { id: "11-3", type: 0, next: [] },
                  { id: "11-4", type: 0, next: [] },
                  { id: "11-5", type: 0, next: [] },
                  { id: "11-6", type: 0, next: [] },
                  { id: "11-7", type: 0, next: [] },
                  { id: "11-8", type: 0, next: [] },
                  { id: "11-9", type: 0, next: [] },
                  { id: "11-10", type: "BATTLE", next: ["11-11"] },
                  { id: "11-11", type: "BOSS", next: [] },
              ],
          ],
      })),
});
