export const assetsManifest = {
    images: [
        // Single background images in /assets
        '/assets/bonfire-bg.webp',
        '/assets/castle-bg-dither-2px.webp',
        '/assets/splashScreenTitle.png',
        '/assets/quest_journal.webp',
        '/assets/map.webp',

        // Armor
        '/assets/sprites/armor/cloth_arm.png',
        '/assets/sprites/armor/cloth_bts.png',
        '/assets/sprites/armor/cloth_hlm.png',
        '/assets/sprites/armor/iron_arm.png',
        '/assets/sprites/armor/iron_bts.png',
        '/assets/sprites/armor/iron_hlm.png',
        '/assets/sprites/armor/leather_arm.png',
        '/assets/sprites/armor/leather_bts.png',
        '/assets/sprites/armor/leather_hood.png',

        // Heroes
        '/assets/sprites/heroes/mage.png',
        '/assets/sprites/heroes/rogue.png',
        '/assets/sprites/heroes/warrior.png',

        // Potions
        '/assets/sprites/potions/hp_pot.png',

        // Trinkets
        '/assets/sprites/trinkets/rouge_trk.png',
        '/assets/sprites/trinkets/warr_trk.png',
        '/assets/sprites/trinkets/wiz_trk.png',

        // Misc sprite files
        '/assets/sprites/book-closed.png',
        '/assets/sprites/book-open.png',
        '/assets/sprites/embark-nav-icon.png',
        '/assets/sprites/exit-nav-icon.png',
        '/assets/sprites/feather.png',
        '/assets/sprites/inventory-nav-icon.png',
        '/assets/sprites/shop-nav-icon.png',
        '/assets/sprites/sword-shiny.png',

        // Backgrounds
        '/assets/battle_bg/castle/1.webp',
        '/assets/battle_bg/castle/2.webp',
        '/assets/battle_bg/castle/3.webp',
        '/assets/battle_bg/castle/4.webp',
        '/assets/battle_bg/castle/5.webp',
        '/assets/battle_bg/castle/6.webp',
        '/assets/battle_bg/castle/7.webp',
        '/assets/battle_bg/castle/8.webp',
        '/assets/battle_bg/castle/9.webp',
        '/assets/battle_bg/castle/10.webp',
        '/assets/battle_bg/castle/11.webp',
        '/assets/battle_bg/castle/12.webp',
        '/assets/battle_bg/castle/13.webp',

        '/assets/battle_bg/caves/1.webp',
        '/assets/battle_bg/caves/2.webp',
        '/assets/battle_bg/caves/3.webp',
        '/assets/battle_bg/caves/4.webp',
        '/assets/battle_bg/caves/5.webp',
        '/assets/battle_bg/caves/6.webp',

        '/assets/battle_bg/desert/1.webp',
        '/assets/battle_bg/desert/2.webp',
        '/assets/battle_bg/desert/3.webp',
        '/assets/battle_bg/desert/4.webp',
        '/assets/battle_bg/desert/5.webp',
        '/assets/battle_bg/desert/6.webp',
        '/assets/battle_bg/desert/7.webp',
        '/assets/battle_bg/desert/8.webp',
        '/assets/battle_bg/desert/9.webp',

        '/assets/battle_bg/forest/1.webp',
        '/assets/battle_bg/forest/2.webp',
        '/assets/battle_bg/forest/3.webp',
        '/assets/battle_bg/forest/4.webp',
        '/assets/battle_bg/forest/5.webp',
        '/assets/battle_bg/forest/6.webp',
        '/assets/battle_bg/forest/7.webp',
        '/assets/battle_bg/forest/8.webp',
        '/assets/battle_bg/forest/9.webp',
        '/assets/battle_bg/forest/10.webp',

        '/assets/battle_bg/mountain/1.webp',
        '/assets/battle_bg/mountain/2.webp',
        '/assets/battle_bg/mountain/3.webp',
        '/assets/battle_bg/mountain/4.webp',
        '/assets/battle_bg/mountain/5.webp',
        '/assets/battle_bg/mountain/6.webp',
        '/assets/battle_bg/mountain/7.webp',
        '/assets/battle_bg/mountain/8.webp',
        '/assets/battle_bg/mountain/9.webp',
        '/assets/battle_bg/mountain/10.webp',

        '/assets/battle_bg/swamp/1.webp',
        '/assets/battle_bg/swamp/2.webp',
        '/assets/battle_bg/swamp/3.webp',
        '/assets/battle_bg/swamp/4.webp',
        '/assets/battle_bg/swamp/5.webp',
        '/assets/battle_bg/swamp/6.webp',
        '/assets/battle_bg/swamp/7.webp',
        '/assets/battle_bg/swamp/8.webp',
        '/assets/battle_bg/swamp/9.webp',

        // Char sheet backgrounds
        '/assets/char_sheet_bg/CASTLE/1.webp',
        '/assets/char_sheet_bg/CAVES/1.webp',
        '/assets/char_sheet_bg/DESERT/1.webp',
        '/assets/char_sheet_bg/FOREST/1.webp',
        '/assets/char_sheet_bg/MOUNTAIN/1.webp',
        '/assets/char_sheet_bg/SWAMP/1.webp',

        // Map backgrounds
        '/assets/map/castle-map.png',
        '/assets/map/caves-map.png',
        '/assets/map/desert-map.png',
        '/assets/map/forest-map.png',
        '/assets/map/mountain-map.png',
        '/assets/map/swamp-map.png',

        // Shop backgrounds
        '/assets/shop_bg/1.webp',
        '/assets/shop_bg/2.webp',
        '/assets/shop_bg/3.webp',
        '/assets/shop_bg/4.webp',
        '/assets/shop_bg/5.webp',
        '/assets/shop_bg/6.webp',
        '/assets/shop_bg/7.webp',
        '/assets/shop_bg/8.webp',
        '/assets/shop_bg/9.webp',
        '/assets/shop_bg/10.webp',
        '/assets/shop_bg/11.webp',
        '/assets/shop_bg/12.webp',
    ],
    data: [
        '/assets/bosses.json',
        '/assets/items.json',
        '/assets/mobs.json',
    ],
    audio: [
        '/assets/audio/bgm/battle-1-bgm.mp3',
        '/assets/audio/bgm/battle-2-bgm.mp3',
        '/assets/audio/bgm/battle-3-bgm.mp3',
        '/assets/audio/bgm/castle-bgm.mp3',
        '/assets/audio/bgm/cave-bgm.mp3',
        '/assets/audio/bgm/desert-bgm.mp3',
        '/assets/audio/bgm/forest-bgm.mp3',
        '/assets/audio/bgm/mountain-bgm.mp3',
        '/assets/audio/bgm/splash-bgm.mp3',
        '/assets/audio/bgm/swamp-bgm.mp3',
        '/assets/audio/bgm/tavern-bgm.wav'
    ],
};